services:
  - type: worker
    name: mafia-auto-join-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python mafia_bot.py
    plan: free
    envVars:
      - key: API_ID
        value: 35614321
      - key: API_HASH
        value: "e0d86345e60444945df2b2d5c7135256"
      - key: STRING_SESSION
  sync: false
  
